# Generated by Django 3.1.5 on 2022-08-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mailing',
            field=models.BooleanField(default=False, help_text='Подключает ежемесячную рассылку по 6 метрикам', verbose_name='рассылка'),
        ),
    ]
