# Generated by Django 3.1.5 on 2021-01-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.TextField(verbose_name='Id метки')),
                ('timestamp', models.DateTimeField(verbose_name='Время создания метрики')),
                ('dx', models.FloatField(verbose_name='Отклонение по оси x')),
                ('dy', models.FloatField(verbose_name='Отклонение по оси y')),
                ('skox', models.FloatField(verbose_name='Крен по оси x')),
                ('skoy', models.FloatField(verbose_name='Крен по оси y')),
            ],
            options={
                'verbose_name': 'метка',
                'verbose_name_plural': 'метки',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='UrlsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, verbose_name='Название')),
                ('priority', models.IntegerField(null=True, verbose_name='Порядок')),
                ('url', models.TextField(null=True, verbose_name='Ссылка')),
                ('is_visible', models.BooleanField(null=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'ссылка',
                'verbose_name_plural': 'ссылки',
                'ordering': ('priority',),
            },
        ),
    ]
